### ISSUE TITLE
How do you link pickers using this library?

### ISSUE THREAD

**Issue by nikiben** [TigorC/ngx-eonasdan-datetimepicker#7]

**Comment by TigorC** [comment]
ngx-eonasdan-datetimepicker is just a angular wrapper for [bootstrap-datetimepicker](http://eonasdan.github.io/bootstrap-datetimepicker/).
All depends from what you want to do. You can find linked pickers example in original plugin documentation [linked-pickers](http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers).
