### ISSUE TITLE
Cannot disable input

### ISSUE THREAD

**Issue by kwiniarski97** [TigorC/ngx-eonasdan-datetimepicker#8]
Is it possible to disable datepicker using reactive forms?

In my component i got:
`<sq-datetimepicker formControlName="startDate" [options]="dateTimePickerOptions" [inputClass]="'form-control normal rounded'" [groupIconClass]="''"></sq-datetimepicker>`

And in my component.ts:
`startDate.disable()` 
however the input is not disabled.

**Comment by kwiniarski97** [comment]
Only way i found i can disable input  is in my html by addding `[readOnly]="true"`

**Comment by TigorC** [comment]
Currently, it's not supported. Yes you should use `readOnly` for this. At the moment I have not the time to support this library :(
